title: "EndoBujo"
second_title: "renouer avec son cycle, en apprendre plus sur l'endométriose."
url: https://endobujo.fr
og_description: EndoBujo est site d'information sur le cycle et l'endométriose/l'adénomyose.
plugins:
  - jekyll-sitemap
  - jekyll-redirect-from
