title: "EndoBujo"
second_title: "carnet de note spécialement pensé pour les personnes atteintes d'endométriose."
url: https://endobujo.fr
og_description: EndoBujo est un carnet de note spécialement pensé pour les personnes atteintes d'endométriose.
plugins:
  - jekyll-sitemap
  - jekyll-redirect-from
